# Generated by Django 5.1.3 on 2024-11-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cedula',
            new_name='cedula_cliente',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='cedula',
            new_name='cedula_vendedor',
        ),
        migrations.RenameField(
            model_name='vendedor',
            old_name='cedula',
            new_name='cedula_vendedor',
        ),
        migrations.AddField(
            model_name='factura',
            name='cedula_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Factura.cliente'),
            preserve_default=False,
        ),
    ]
